### PR TITLE
feat: support macro in query

### PR DESCRIPTION
**Pull request by JimYan**
fix from webpack@4 ,the customer options is't support.

### CODE REVIEW

**Comment by devlinjunker** [comment]
Oh. I didn’t see this when I created my PR. This doesn’t seem like a good sign that it’s been sitting here for almost a year...

@emaphp are you around? Should this be ported to a new maintainer?

**Comment by emaphp** [comment]
@devlinjunker Sorry guys, It's been very difficult to have the time to maintain my repos. I just published a v1.1 that includes the changes introduced @JimYan. I was planning to add them on the v2.0 branch as well. Thanks for your work.

**Comment by devlinjunker** [comment]
🎉 thanks for the quick response @emaphp!

**Comment by devlinjunker** [comment]
also, excited for v2.0!

**Pull request merged**
