### PR TITLE
Webpack 5 compatibility

### PR DESCRIPTION
**Pull request by idudinov**
The main change here was to get rid of custom `file-loader` usage. 
Of course I'm not aware why it was initially introduced, but from my findings and use cases the removal doesn't break anything but makes our codebase work as it was for webpack 4. I'd appreciate any feedback on this suggestion.

### CODE REVIEW

**Comment by Hirbod** [comment]
While I did not encounter any issues with webpack 5 before, this PR did not break anything for me either.

**Comment by ryon137** [comment]
Any reason why this was not merged?

**Comment by emaphp** [comment]
> Any reason why this was not merged?

life

**Comment by idudinov** [comment]
@emaphp thanks for merging and releasing new version!

**Pull request merged**
